services:
  - type: web
    name: masterlexicon-enterprise
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: SUPER_ENTERPRISE_KEY_2026
      - key: DATABASE_URL
        sync: false
